apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  labels:
     grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://grafana-mimir-gateway.grafana-mimir.svc.cluster.local/prometheus
      jsonData:
        httpMethod: POST
        prometheusType: Mimir
