apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-datasource
  labels:
     grafana_datasource: "1"
data:
  mimir-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Mimir
      type: prometheus
      access: proxy
      url: http://localhost:9090
      jsonData:
        httpMethod: POST
        prometheusType: Mimir
