apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
data:
  config: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    // remote write
    prometheus.remote_write "default" {
      endpoint {
        url = "http://grafana-mimir-gateway.grafana-mimir.svc.cluster.local/api/v1/push"
      }
    }

    loki.write "local" {
      endpoint {
        url = "http://grafana-loki-loki-distributed-gateway.grafana-loki.svc.cluster.local/loki/api/v1/push"
      }
    }

    // discovery
    prometheus.exporter.agent "agent" {}

    discovery.kubernetes "nodes" {
      role = "node"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    // prometheus scrape
    prometheus.scrape "agent" {
      targets    = prometheus.exporter.agent.agent.targets
      forward_to = [prometheus.remote_write.default.receiver]
    }

    prometheus.operator.servicemonitors "servicemonitors" {
      forward_to = [prometheus.remote_write.default.receiver]
    }

    // loki source
    loki.source.journal "read"  {
      forward_to    = [loki.write.local.receiver]
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.write.local.receiver]
    }

    loki.source.kubernetes_events "events" {
      log_format = "json"
      forward_to = [loki.write.local.receiver]
    }
