defaultRules:
  create: true
  rules:
    kubeProxy: false
global:
  rbac:
    create: false
    pspEnabled: false
grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      enabled: true
# since k3s expose every metrics except etcd, we have to hack
# we have to relabel metrics with jobs to get dashboards working
# https://github.com/k3s-io/k3s/issues/3619
kubelet:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: "scheduler_(.+)"
        targetLabel: "job"
        replacement: "kube-scheduler"
      - sourceLabels: [__name__]
        regex: "kubeproxy_(.+)"
        targetLabel: "job"
        replacement: "kube-proxy"
kubeApiServer:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
prometheus:
  enabled: false
prometheusOperator:
  enabled: false
alertmanager:
  enabled: false
