querier:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-bucket

loki:
  config: |
    storageConfig:
      bucketNames:
        chunks: loki/chunks
        ruler: loki/ruler
        admin: loki/admin
      type: s3
      s3:
        endpoint: s3://s3.unicornafk.fr
        region: eu-west-1
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
        s3ForcePathStyle: false
        insecure: false

monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false

gateway:
  enabled: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "vault"
    cert-manager.io/private-key-algorithm: "RSA"
    cert-manager.io/private-key-size: "4096"
    traefik.ingress.kubernetes.io/router.middlewares: loki-basic-auth@kubernetescrd
  hosts:
    - host: loki.unicornafk.fr
      paths:
        - path: /
  ingressClassName: "ingress-internal"
  tls:
    - secretName: loki.unicornafk.fr
      hosts:
        - loki.unicornafk.fr