querier:
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-bucket
    - configMapRef:
        name: loki-bucket

loki:
  annotations:
    reloader.stakater.com/auto: "true"
  storage:
    bucketNames:
      chunks: ${BUCKET_NAME}/chunks
      ruler: ${BUCKET_NAME}/ruler
      admin: ${BUCKET_NAME}/admin
    type: s3
    s3:
      endpoint: s3://${BUCKET_HOST}
      region: eu-west-1
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      s3ForcePathStyle: false
      insecure: false

monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false

serviceMonitor:
  enabled: true

gateway:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "vault"
      cert-manager.io/private-key-algorithm: "RSA"
      cert-manager.io/private-key-size: "4096"
    hosts:
      - host: loki.unicornafk.fr
    ingressClassName: "ingress-internal"
    tls:
      - secretName: loki.unicornafk.fr
        hosts:
          - loki.unicornafk.fr