controller:
  extraAnnotations:
    reloader.stakater.com/auto: "true"
agent:
  enableReporting: false
  mode: 'flow'
  configMap:
    create: false
    name: grafana-agent-config
    key: config
  clustering:
    enabled: true
crds:
  create: false
configReloader:
  enabled: false