apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

helmCharts:
- name: keycloak
  releaseName: keycloak
  namespace: keycloak
  repo: https://charts.bitnami.com/bitnami
  version: 17.0.0
  valuesFile: values.yaml
