replicaCount: 2

auth:
  adminUser: "<path:secret/data/homelab/prod/argocd/keycloak#ADMIN_USER>"
  adminPassword: "<path:secret/data/homelab/prod/argocd/keycloak#ADMIN_PASSWORD>"

postgresql:
  enabled: false

externalDatabase:
  host: "pgsql-homelab-keycloak-cluster"
  port: 5432
  user: "<path:secret/data/homelab/prod/argocd/keycloak#POSTGRESQL_USERNAME>"
  database: "<path:secret/data/homelab/prod/argocd/keycloak#POSTGRESQL_DATABASE>"
  existingSecret: "postgres.homelab-keycloak-cluster.credentials"
  existingSecretPasswordKey: "data.password"

production: true
proxy: edge

ingress:
  enabled: true
  ingressClassName: "traefik-external"
  hostname: sso.unicornafk.fr
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls: true