operator:
  console:
    enabled: false
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "vault"
      cert-manager.io/private-key-algorithm: "RSA"
      cert-manager.io/private-key-size: "4096"
    hosts:
      - console.minio.unicornafk.fr
    ingressClassName: "ingress-internal"
    tls:
      - secretName: console.minio.unicornafk.fr
        hosts:
          - console.minio.unicornafk.fr
