apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: keycloak
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app.kubernetes.io/name: keycloak-postgres
    app.kubernetes.io/instance: keycloak-postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: keycloak
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-postgres
      app.kubernetes.io/instance: keycloak-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak-postgres
        app.kubernetes.io/instance: keycloak-postgres
      annotations:
        vault.hashicorp.com/tls-secret: "homelab-ca"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'keycloak'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/homelab/prod/keycloak'
        vault.hashicorp.com/agent-inject-template-config: |
         {{- with secret "secret/data/homelab/prod/keycloak" -}}
          export POSTGRES_USER="{{ .Data.data.POSTGRESQL_USER }}"
          export POSTGRES_PASSWORD="{{ .Data.data.POSTGRESQL_PASSWORD }}"
         {{- end }}
    spec:
      serviceAccountName: keycloak
      containers:
        - name: postgres
          image: postgres:16.0
          command:
            - /bin/bash
            - -c
          args:
            - source /vault/secrets/config && docker-entrypoint.sh postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-pv-claim
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pv-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
