apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/instance: keycloak
      annotations:
        vault.hashicorp.com/tls-secret: "homelab-ca"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'keycloak'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/homelab/prod/keycloak'
        vault.hashicorp.com/agent-inject-template-config: |
         {{- with secret "secret/data/homelab/prod/keycloak" -}}
          export KC_DB_USERNAME="{{ .Data.data.POSTGRESQL_USER }}"
          export KC_DB_PASSWORD="{{ .Data.data.POSTGRESQL_PASSWORD }}"
          export KEYCLOAK_ADMIN="{{ .Data.data.ADMIN_USER }}"
          export KEYCLOAK_ADMIN_PASSWORD="{{ .Data.data.ADMIN_PASSWORD }}"
         {{- end }}
    spec:
      serviceAccountName: keycloak
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:22.0.4
        command:
          - /bin/bash
          - -c
        args:
          - source /vault/secrets/config && /opt/keycloak/bin/kc.sh start
        env:
          - name: KC_PROXY
            value: "edge"
          - name: KC_HEALTH_ENABLED
            value: "true"
          - name: KC_METRICS_ENABLED
            value: "true"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "false"
          - name: KC_LOG_LEVEL
            value: INFO
          - name: KC_DB
            value: postgres
          - name: KC_HOSTNAME
            value: sso.unicornafk.fr
          - name: KC_DB_URL
            value: jdbc:postgresql://postgres/keycloak
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 250
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 500
          periodSeconds: 30
        resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"