apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: homelab-keycloak-cluster
  namespace: keycloak
spec:
  teamId: "homelab"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    "<path:secret/data/homelab/prod/argocd/keycloak#POSTGRESQL_USERNAME>":
      - superuser
      - createdb
  databases:
    "<path:secret/data/homelab/prod/argocd/keycloak#POSTGRESQL_DATABASE>": "<path:secret/data/homelab/prod/argocd/keycloak#POSTGRESQL_USERNAME>"
  postgresql:
    version: "16"