apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-argocd
spec:
  generators:
  - list:
      elements:
        - appName: external-secrets
          namespace: external-secrets
        - appName: keycloak
          namespace: keycloak
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/M0NsTeRRR/test_argocd.git
        targetRevision: main
        path: argocd/{{appName}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
