---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-vault
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "loki"
          serviceAccountRef:
            name: "loki-vault"
      caProvider:
        type: "ConfigMap"
        # https://github.com/external-secrets/external-secrets/issues/1024
        namespace: "loki"
        name: "homelab-ca"
        key: "ca.crt"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-basic-auth-vault
spec:
  refreshInterval: "1m"
  target:
    creationPolicy: "Owner"
    deletionPolicy: "Retain"
  secretStoreRef:
    kind: SecretStore
    name: vault
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/homelab/prod/loki
        property: BASIC_USERNAME
    - secretKey: password
      remoteRef:
        key: secret/data/homelab/prod/loki
        property: BASIC_PASSWORD
