---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-middleware
spec:
  basicAuth:
    removeHeader: true
    secret: loki-basic-auth-vault
  headers:
    customRequestHeaders:
      X-Scope-OrgID: "homelab"