apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

helmCharts:
- name: operator
  releaseName: minio
  namespace: minio
  repo: https://operator.min.io
  version: 5.0.11
  valuesFile: values.yaml
