admin:
  existingSecret: grafana-vault
  userKey: ADMIN_USER
  passwordKey: ADMIN_PASSWORD

sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki-loki-distributed-gateway.loki.svc.cluster.local
      access: proxy
      jsonData:
        maxLines: 1000

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "vault"
    cert-manager.io/private-key-algorithm: "RSA"
    cert-manager.io/private-key-size: "4096"
  hosts:
    - monitoring.unicornafk.fr
  ingressClassName: "ingress-internal"
  tls:
    - secretName: monitoring.unicornafk.fr
      hosts:
        - monitoring.unicornafk.fr