annotations:
  reloader.stakater.com/auto: "true"

admin:
  existingSecret: grafana-vault
  userKey: ADMIN_USER
  passwordKey: ADMIN_PASSWORD

sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
  datasources:
    enabled: true
    searchNamespace: ALL

dashboardProviders:
  dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: true
     editable: true
     options:
       path: /var/lib/grafana/dashboards

dashboards:
  default:
    Traefik:
      gnetId: 17347
      revision: 7
      datasource: Prometheus
    Argocd:
      gnetId: 14584
      revision: 1
      datasource: Prometheus
    External-dns:
      gnetId: 15038
      revision: 3
      datasource: Prometheus
    Ceph-cluster:
      gnetId: 2842
      revision: 17
      datasource: Prometheus
    Ceph-osd-single:
      gnetId: 5336
      revision: 9
      datasource: Prometheus
    Ceph-pools:
      gnetId: 5342
      revision: 9
      datasource: Prometheus
    External-secrets:
      url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
    Keycloak:
      gnetId: 14607
      revision: 1
      datasource: Prometheus
    Cert-manager:
      url: https://gitlab.com/uneeq-oss/cert-manager-mixin/-/raw/master/dashboards/cert-manager.json

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "vault"
    cert-manager.io/private-key-algorithm: "RSA"
    cert-manager.io/private-key-size: "4096"
  hosts:
    - monitoring.unicornafk.fr
  ingressClassName: "ingress-internal"
  tls:
    - secretName: monitoring.unicornafk.fr
      hosts:
        - monitoring.unicornafk.fr