serviceMonitor:
  enabled: true
  namespace: grafana-agent
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "vault"
    cert-manager.io/private-key-algorithm: "RSA"
    cert-manager.io/private-key-size: "4096"
  hosts:
    - host: pushgateway.unicornafk.fr
  className: "ingress-internal"
  tls:
    - secretName: mimir.unicornafk.fr
      hosts:
        - mimir.unicornafk.fr